"""
pipeline/rbac.py

Role-Based Access Control for persona-filtered API responses.

Personas:
  - gm:
      Full business access including revenue, PVM decomposition,
      confidence, evidence, root causes, and action recommendations.

  - ops_lead:
      Operational access only. No revenue, PVM financial decomposition,
      financial impact, or raw confidence scores.

  - analyst:
      Full analytical access including raw scores, graph topology,
      correlation matrix, and PVM decomposition.

RBAC is applied at the RESPONSE layer:
    full pipeline result
            ↓
        RBAC filter
            ↓
      persona-specific response

The underlying pipeline always runs using the complete dataset.
RBAC does not modify the underlying investigation result.
"""

from __future__ import annotations

from typing import Dict, Any, List


# ---------------------------------------------------------------------------
# KPI groups
# ---------------------------------------------------------------------------

CORE_KPIS = [
    "revenue",
    "order_cancellation_rate",
    "fulfillment_delay_rate",
    "support_ticket_volume",
    "warehouse_staffing_level",
]

# PVM inputs are financial/business-driver variables.
PVM_KPIS = [
    "unit_price",
    "marketing_spend",
    "seasonal_index",
]

# PVM contribution nodes generated by pvm_decomposition.py.
PVM_NODES = [
    "pvm_price",
    "pvm_marketing",
    "pvm_seasonal",
    "pvm_volume",
]


# ---------------------------------------------------------------------------
# Persona definitions
# ---------------------------------------------------------------------------

PERSONA_DEFINITIONS: Dict[str, Dict[str, Any]] = {

    # -----------------------------------------------------------------------
    # General Manager
    # -----------------------------------------------------------------------
    "gm": {
        "label": "General Manager",
        "description": (
            "Business-level access to KPI health, financial impact, "
            "root causes, confidence, evidence, PVM decomposition, "
            "and action recommendations."
        ),

        # Keep these UI metadata fields unchanged in spirit from the
        # original implementation.
        "color": "#7C3AED",
        "icon": "crown",

        # GM can see the complete business KPI picture.
        "allowed_kpis": CORE_KPIS + PVM_KPIS,

        # Fields available in the investigation response.
        "allowed_fields": [
            "confidence",
            "confidence_score",
            "verdict",
            "action",
            "root_causes",
            "evidence_summary",
            "causal_chain",
            "challenge_summary",
            "challenge_result",
            "pvm_decomposition",
            "evidence_graph",
            "correlation_matrix",
            "kpi_health",
            "materiality",
        ],

        "can_see_raw_scores": True,
        "can_see_graph_topology": True,
        "can_see_financial_impact": True,
        "can_see_pvm": True,
    },

    # -----------------------------------------------------------------------
    # Operations Lead
    # -----------------------------------------------------------------------
    "ops_lead": {
        "label": "Operations Lead",
        "description": (
            "Operational KPI access focused on fulfillment, staffing, "
            "support, and cancellations. Financial revenue and PVM "
            "information are restricted."
        ),

        "color": "#059669",
        "icon": "settings",

        # Deliberately excludes revenue and PVM financial drivers.
        "allowed_kpis": [
            "fulfillment_delay_rate",
            "support_ticket_volume",
            "warehouse_staffing_level",
            "order_cancellation_rate",
        ],

        "allowed_fields": [
            "verdict",
            "action",
            "root_causes",
            "evidence_summary",
            "causal_chain",
            "challenge_summary",
            "challenge_result",
            "kpi_health",
            "materiality",
            "evidence_graph",
        ],

        "can_see_raw_scores": False,
        "can_see_graph_topology": True,
        "can_see_financial_impact": False,
        "can_see_pvm": False,
    },

    # -----------------------------------------------------------------------
    # Analyst
    # -----------------------------------------------------------------------
    "analyst": {
        "label": "Data Analyst",
        "description": (
            "Full analytical access including raw sub-scores, "
            "graph topology, correlations, PVM decomposition, "
            "and detailed investigation evidence."
        ),

        "color": "#0284C7",
        "icon": "chart",

        # Analyst gets all business and PVM KPIs.
        "allowed_kpis": CORE_KPIS + PVM_KPIS,

        "allowed_fields": [
            "confidence",
            "confidence_score",
            "verdict",
            "action",
            "root_causes",
            "evidence_summary",
            "causal_chain",
            "challenge_summary",
            "challenge_result",
            "pvm_decomposition",
            "evidence_graph",
            "correlation_matrix",
            "raw_sub_scores",
            "kpi_health",
            "materiality",
        ],

        "can_see_raw_scores": True,
        "can_see_graph_topology": True,
        "can_see_financial_impact": True,
        "can_see_pvm": True,
    },
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _filter_kpi_mapping(
    mapping: Dict[str, Any],
    allowed_kpis: List[str],
) -> Dict[str, Any]:
    """
    Keep only KPI keys explicitly allowed for the persona.
    """
    if not isinstance(mapping, dict):
        return {}

    return {
        key: value
        for key, value in mapping.items()
        if key in allowed_kpis
    }


def _filter_root_causes(
    root_causes: Any,
    persona: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """
    Filter root-cause candidates according to persona permissions.

    PVM contribution nodes are allowed only for personas with PVM access.
    """

    if not isinstance(root_causes, list):
        return []

    allowed_kpis = set(persona["allowed_kpis"])
    can_see_pvm = persona["can_see_pvm"]
    can_see_raw_scores = persona["can_see_raw_scores"]

    filtered = []

    for root_cause in root_causes:

        if not isinstance(root_cause, dict):
            continue

        kpi = root_cause.get("kpi")

        if not isinstance(kpi, str):
            continue

        # Normal KPI permission.
        allowed = kpi in allowed_kpis

        # PVM contribution-node permission.
        if kpi in PVM_NODES:
            allowed = can_see_pvm

        if not allowed:
            continue

        item = dict(root_cause)

        # Remove internal/raw scoring information for restricted personas.
        if not can_see_raw_scores:
            item.pop("graph_score", None)
            item.pop("composite_score", None)
            item.pop("evidence_score", None)

            # These may contain numerical impact information.
            item.pop("normalized_impact", None)
            item.pop("effect_size", None)
            item.pop("impact_score", None)

        # Financial PVM contribution is hidden from non-financial personas.
        if not persona["can_see_financial_impact"]:
            item.pop("contribution_magnitude_usd", None)
            item.pop("contribution_score", None)

        filtered.append(item)

    return filtered


def _filter_causal_chain(
    causal_chain: Any,
    persona: Dict[str, Any],
) -> List[str]:
    """
    Filter causal-chain nodes according to persona permissions.

    PVM nodes are retained only when the persona has PVM access.
    """

    if not isinstance(causal_chain, list):
        return []

    allowed_kpis = set(persona["allowed_kpis"])
    can_see_pvm = persona["can_see_pvm"]

    result = []

    for kpi in causal_chain:

        if not isinstance(kpi, str):
            continue

        if kpi in PVM_NODES:
            if can_see_pvm:
                result.append(kpi)
        elif kpi in allowed_kpis:
            result.append(kpi)

    return result


def _filter_evidence_graph(
    evidence_graph: Dict[str, Any],
    persona: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Filter Evidence Graph nodes and links.

    The graph topology itself is available to personas with
    can_see_graph_topology=True.

    Financial/PVM nodes remain hidden when PVM access is disabled.
    """

    if not isinstance(evidence_graph, dict):
        return {}

    if not persona["can_see_graph_topology"]:
        return {}

    allowed_kpis = set(persona["allowed_kpis"])
    can_see_pvm = persona["can_see_pvm"]

    def node_allowed(node_id: str) -> bool:
        if node_id in PVM_NODES:
            return can_see_pvm

        return node_id in allowed_kpis

    graph_data = evidence_graph.get("graph_data", {})

    raw_nodes = graph_data.get("nodes", [])
    raw_links = graph_data.get("links", [])

    nodes = []
    for node in raw_nodes:

        if not isinstance(node, dict):
            continue

        node_id = node.get("id")

        if not isinstance(node_id, str):
            continue

        if not node_allowed(node_id):
            continue

        filtered_node = dict(node)

        # Restrict raw centrality information for ops_lead.
        if not persona["can_see_raw_scores"]:
            filtered_node.pop("centrality", None)

        nodes.append(filtered_node)

    allowed_node_ids = {
        node.get("id")
        for node in nodes
        if isinstance(node, dict)
    }

    links = []

    for link in raw_links:

        if not isinstance(link, dict):
            continue

        source = link.get("source")
        target = link.get("target")

        if (
            source not in allowed_node_ids
            or target not in allowed_node_ids
        ):
            continue

        filtered_link = dict(link)

        # Raw graph weights/correlations are analytical information.
        if not persona["can_see_raw_scores"]:
            filtered_link.pop("weight", None)
            filtered_link.pop("correlation", None)

        links.append(filtered_link)

    # Driver ranking.
    driver_ranking = []

    for ranking in evidence_graph.get("driver_ranking", []):

        if not isinstance(ranking, dict):
            continue

        kpi = ranking.get("kpi")

        if not isinstance(kpi, str):
            continue

        if not node_allowed(kpi):
            continue

        item = dict(ranking)

        if not persona["can_see_raw_scores"]:
            item.pop("score", None)

        driver_ranking.append(item)

    result = {
        "nodes": nodes,
        "links": links,
        "driver_ranking": driver_ranking,
    }

    # Analyst can see the graph's detailed correlation matrix.
    if persona["can_see_raw_scores"]:
        result["correlation_matrix"] = _filter_correlation_matrix(
            evidence_graph.get("correlation_matrix", {}),
            persona,
        )

    return result


def _filter_correlation_matrix(
    correlation_matrix: Any,
    persona: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Filter correlation pairs so that restricted KPI/PVM information
    does not leak to the persona.
    """

    if not isinstance(correlation_matrix, dict):
        return {}

    allowed_kpis = set(persona["allowed_kpis"])
    can_see_pvm = persona["can_see_pvm"]

    def allowed_node(node: str) -> bool:
        if node in PVM_NODES:
            return can_see_pvm

        return node in allowed_kpis

    filtered = {}

    for pair, value in correlation_matrix.items():

        if not isinstance(pair, str):
            continue

        # Evidence Graph uses "source→target".
        if "→" not in pair:
            continue

        source, target = pair.split("→", 1)

        if allowed_node(source) and allowed_node(target):
            filtered[pair] = value

    return filtered


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_personas() -> List[Dict[str, Any]]:
    """
    Returns persona definitions for the /personas endpoint.

    Internal permission fields are included because this endpoint is
    intended for the application's persona configuration/UI.
    """

    return [
        {
            "id": persona_id,
            **{
                key: value
                for key, value in definition.items()
            },
        }
        for persona_id, definition in PERSONA_DEFINITIONS.items()
    ]


def filter_for_persona(
    investigation_result: Dict[str, Any],
    persona_id: str,
) -> Dict[str, Any]:
    """
    Filter a complete investigation result for a specific persona.

    Args:
        investigation_result:
            Full pipeline result before RBAC filtering.

        persona_id:
            "gm", "ops_lead", or "analyst".

    Returns:
        Persona-specific investigation result.

    Security behavior:
        Unknown personas default to the most restrictive persona
        (ops_lead).

    Important:
        This function never mutates investigation_result.
    """

    if not isinstance(investigation_result, dict):
        raise TypeError(
            "investigation_result must be a dictionary."
        )

    persona = PERSONA_DEFINITIONS.get(persona_id)

    if persona is None:
        # Fail closed.
        persona_id = "ops_lead"
        persona = PERSONA_DEFINITIONS["ops_lead"]

    filtered: Dict[str, Any] = {}

    # -----------------------------------------------------------------------
    # Base investigation metadata
    # -----------------------------------------------------------------------

    for field in [
        "region_id",
        "scenario",
        "investigation_id",
        "timestamp",
    ]:
        if field in investigation_result:
            filtered[field] = investigation_result[field]

    # -----------------------------------------------------------------------
    # KPI health
    # -----------------------------------------------------------------------

    if "kpi_health" in investigation_result:
        filtered["kpi_health"] = _filter_kpi_mapping(
            investigation_result["kpi_health"],
            persona["allowed_kpis"],
        )

    # -----------------------------------------------------------------------
    # Materiality
    # -----------------------------------------------------------------------

    if "materiality" in investigation_result:

        materiality = investigation_result["materiality"]

        if isinstance(materiality, dict):

            allowed = set(persona["allowed_kpis"])

            filtered_materiality = {
                "material_kpis": [
                    k
                    for k in materiality.get("material_kpis", [])
                    if k in allowed
                ],
                "any_material": materiality.get(
                    "any_material",
                    False,
                ),
                "signal_strength": materiality.get(
                    "signal_strength"
                ),
                "kpi_results": {
                    k: v
                    for k, v in materiality.get(
                        "kpi_results",
                        {},
                    ).items()
                    if k in allowed
                },
            }

            filtered["materiality"] = filtered_materiality

    # -----------------------------------------------------------------------
    # Confidence
    # -----------------------------------------------------------------------

    if "confidence" in investigation_result:

        confidence = investigation_result["confidence"]

        if isinstance(confidence, dict):

            filtered_confidence = {
                "verdict": confidence.get("verdict"),
                "explanation": confidence.get("explanation"),
            }

            if persona["can_see_raw_scores"]:

                filtered_confidence["score"] = confidence.get(
                    "score"
                )

                filtered_confidence["sub_scores"] = confidence.get(
                    "sub_scores"
                )

                filtered_confidence["weights"] = confidence.get(
                    "weights"
                )

            filtered["confidence"] = filtered_confidence

    # -----------------------------------------------------------------------
    # Verdict
    # -----------------------------------------------------------------------

    if "verdict" in investigation_result:
        filtered["verdict"] = investigation_result["verdict"]

    # -----------------------------------------------------------------------
    # Primary cause
    # -----------------------------------------------------------------------

    if "primary_cause" in investigation_result:
        primary_cause = investigation_result["primary_cause"]
        if isinstance(primary_cause, dict):
            kpi = primary_cause.get("kpi")
            if kpi in persona["allowed_kpis"] or (kpi in PVM_NODES and persona["can_see_pvm"]):
                filtered_pc = dict(primary_cause)
                if not persona["can_see_raw_scores"]:
                    filtered_pc.pop("graph_score", None)
                    filtered_pc.pop("composite_score", None)
                    filtered_pc.pop("evidence_score", None)
                    filtered_pc.pop("normalized_impact", None)
                    filtered_pc.pop("effect_size", None)
                    filtered_pc.pop("impact_score", None)
                if not persona["can_see_financial_impact"]:
                    filtered_pc.pop("contribution_magnitude_usd", None)
                    filtered_pc.pop("contribution_score", None)
                filtered["primary_cause"] = filtered_pc
        elif isinstance(primary_cause, str):
            if primary_cause in persona["allowed_kpis"] or (primary_cause in PVM_NODES and persona["can_see_pvm"]):
                filtered["primary_cause"] = primary_cause

    # -----------------------------------------------------------------------
    # Action recommendation
    # -----------------------------------------------------------------------

    if "action" in investigation_result:

        action = investigation_result["action"]

        if isinstance(action, dict):

            filtered_action = dict(action)

            if not persona["can_see_financial_impact"]:

                # Financial fields that must not reach ops_lead.
                for field in [
                    "estimated_impact",
                    "estimated_impact_usd",
                    "revenue_impact",
                    "revenue_recovery_estimate",
                    "financial_impact",
                    "contribution_magnitude_usd",
                ]:
                    filtered_action.pop(field, None)

            filtered["action"] = filtered_action

    # -----------------------------------------------------------------------
    # Root causes
    # -----------------------------------------------------------------------

    if (
        "root_causes" in investigation_result
        and "root_causes" in persona["allowed_fields"]
    ):
        filtered["root_causes"] = _filter_root_causes(
            investigation_result["root_causes"],
            persona,
        )

    # -----------------------------------------------------------------------
    # Evidence summary
    # -----------------------------------------------------------------------

    if (
        "evidence_summary" in investigation_result
        and "evidence_summary" in persona["allowed_fields"]
    ):
        filtered["evidence_summary"] = (
            investigation_result["evidence_summary"]
        )

    # -----------------------------------------------------------------------
    # Causal chain
    # -----------------------------------------------------------------------

    if (
        "causal_chain" in investigation_result
        and "causal_chain" in persona["allowed_fields"]
    ):
        filtered["causal_chain"] = _filter_causal_chain(
            investigation_result["causal_chain"],
            persona,
        )

    # Compatibility with root_cause.py's temporal_sequence.
    elif (
        "temporal_sequence" in investigation_result
        and "causal_chain" in persona["allowed_fields"]
    ):
        filtered["temporal_sequence"] = _filter_causal_chain(
            investigation_result["temporal_sequence"],
            persona,
        )

    # -----------------------------------------------------------------------
    # Challenge Engine
    # -----------------------------------------------------------------------

    if (
        "challenge_result" in investigation_result
        and (
            "challenge_result" in persona["allowed_fields"]
            or "challenge_summary" in persona["allowed_fields"]
        )
    ):
        filtered["challenge_result"] = (
            investigation_result["challenge_result"]
        )

    # -----------------------------------------------------------------------
    # Evidence Graph
    # -----------------------------------------------------------------------

    if "evidence_graph" in investigation_result:
        graph = _filter_evidence_graph(
            investigation_result["evidence_graph"],
            persona,
        )

        if graph:
            filtered["evidence_graph"] = graph

    # -----------------------------------------------------------------------
    # PVM decomposition
    # -----------------------------------------------------------------------

    if (
        "pvm_decomposition" in investigation_result
        and persona["can_see_pvm"]
        and persona["can_see_financial_impact"]
    ):
        filtered["pvm_decomposition"] = (
            investigation_result["pvm_decomposition"]
        )

    # -----------------------------------------------------------------------
    # Raw sub-scores
    # -----------------------------------------------------------------------

    if (
        persona["can_see_raw_scores"]
        and "raw_sub_scores" in investigation_result
        and "raw_sub_scores" in persona["allowed_fields"]
    ):
        filtered["raw_sub_scores"] = dict(
            investigation_result.get(
                "raw_sub_scores",
                {},
            )
        )

    # -----------------------------------------------------------------------
    # Correlation matrix
    # -----------------------------------------------------------------------

    if (
        persona["can_see_raw_scores"]
        and "correlation_matrix" in investigation_result
        and "correlation_matrix" in persona["allowed_fields"]
    ):
        filtered["correlation_matrix"] = _filter_correlation_matrix(
            investigation_result.get(
                "correlation_matrix",
                {},
            ),
            persona,
        )

    # -----------------------------------------------------------------------
    # Telemetry
    # -----------------------------------------------------------------------

    if "telemetry" in investigation_result:

        telemetry = investigation_result["telemetry"]

        if isinstance(telemetry, dict):

            # Telemetry is operational metadata rather than business KPI
            # data. Keep it available, but hide potentially sensitive
            # token/cost details from the operational persona.
            if persona_id == "ops_lead":

                safe_telemetry = dict(telemetry)

                for field in [
                    "token_count",
                    "input_tokens",
                    "output_tokens",
                    "total_tokens",
                    "cost",
                    "estimated_cost",
                    "llm_cost",
                ]:
                    safe_telemetry.pop(field, None)

                filtered["telemetry"] = safe_telemetry

            else:
                filtered["telemetry"] = dict(telemetry)

    # -----------------------------------------------------------------------
    # Persona context
    # -----------------------------------------------------------------------

    all_business_kpis = CORE_KPIS + PVM_KPIS

    filtered["persona_context"] = {
        "persona_id": persona_id,
        "label": persona["label"],
        "description": persona["description"],
        "color": persona["color"],

        "restricted_kpis_hidden": [
            kpi
            for kpi in all_business_kpis
            if kpi not in persona["allowed_kpis"]
        ],

        "pvm_access": persona["can_see_pvm"],
        "financial_impact_access": persona["can_see_financial_impact"],
        "raw_score_access": persona["can_see_raw_scores"],
        "graph_topology_access": persona["can_see_graph_topology"],
    }

    return filtered